### PR TITLE
Bumped to 2021.331.0 compat

### PR DESCRIPTION
**Pull request by Thesola10**
Some changes which reflect the latest osu! ruleset template, by deprecating the osu! submodule (too heavy) in favor of NuGet packages, and fixed some random prototype

### CODE REVIEW

**Comment by Thesola10** [comment]
This fixes #7

**Comment by Thesola10** [comment]
Possibly closes #5 as well

**Comment by Artemis-chan** [comment]
oh thanks, ill test it and merge tomorrow. i've not been able to work on this for a while so i havent done any updates. I really appreciate the commits.

**Comment by Thesola10** [comment]
> oh thanks, ill test it and merge tomorrow. i've not been able to work on this for a while so i havent done any updates. I really appreciate the commits.

fwiw i tested it on lazer on Linux, only replays and difficulty ratings don't work

**Comment by Thesola10** [comment]
i might start working on [this](https://github.com/thesola10/osu-DIVA/projects/1)...

**Comment by Artemis-chan** [comment]
im on windows and the tests project is not working, also theres some deprecated code. I'm looking into it rn

**Comment by Artemis-chan** [comment]
turns out it was just framework mismatch, just had to bump to `net5.0`

**Pull request merged**
